/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    MazBtn: typeof import('maz-ui/components/MazBtn')['default']
    MazDialog: typeof import('maz-ui/components/MazDialog')['default']
    MazInputNumber: typeof import('maz-ui/components/MazInputNumber')['default']
    MazSelect: typeof import('maz-ui/components/MazSelect')['default']
    MazTextarea: typeof import('maz-ui/components/MazTextarea')['default']
  }
}
